import type { ScenarioPreset } from "./types";

export const scenarioPresets: ScenarioPreset[] = [
  {
    id: "weekend-binge",
    name: "Weekend binge",
    summary: "Higher alcohol load across a short burst, then a sharp stop.",
    inputs: {
      substance: "alcohol",
      doseAmount: 76,
      frequencyPerDay: 3,
      daysInRow: 2,
      timeOfDay: 21,
      sleepAmount: 5.5,
      baselineStress: 44,
      baselineAnxiety: 40,
      traumaSensitivity: 38,
      foodHydrationQuality: 42,
      stoppedSuddenly: true,
    },
  },
  {
    id: "three-nights-drinking-stop",
    name: "3 nights drinking then stop",
    summary: "Repeated evening drinking with rebound anxiety and shakiness risk after stopping.",
    inputs: {
      substance: "alcohol",
      doseAmount: 62,
      frequencyPerDay: 2,
      daysInRow: 3,
      timeOfDay: 20,
      sleepAmount: 6,
      baselineStress: 50,
      baselineAnxiety: 52,
      traumaSensitivity: 48,
      foodHydrationQuality: 55,
      stoppedSuddenly: true,
    },
  },
  {
    id: "nightly-weed-pause",
    name: "Nightly weed then pause",
    summary: "Frequent cannabis use that softens tension at first, then leaves a keyed-up pause.",
    inputs: {
      substance: "cannabis",
      doseAmount: 54,
      frequencyPerDay: 1,
      daysInRow: 7,
      timeOfDay: 22,
      sleepAmount: 6.8,
      baselineStress: 58,
      baselineAnxiety: 55,
      traumaSensitivity: 60,
      foodHydrationQuality: 61,
      stoppedSuddenly: true,
    },
  },
  {
    id: "alcohol-poor-sleep",
    name: "Alcohol + poor sleep",
    summary: "Lower overnight recovery makes rebound anxiety and instability show up faster.",
    inputs: {
      substance: "alcohol",
      doseAmount: 48,
      frequencyPerDay: 2,
      daysInRow: 4,
      timeOfDay: 19,
      sleepAmount: 4.8,
      baselineStress: 64,
      baselineAnxiety: 57,
      traumaSensitivity: 50,
      foodHydrationQuality: 45,
      stoppedSuddenly: true,
    },
  },
];